"""
Wrapper function that website can call & get formatted text schedules back

Argument (to file): a string "['class1', 'class2', ..., 'classN']" which the 
website will provide

Returns: Prints out a formatted schedule generated by problem.py
"""

import sys
import problem


def interpretInput():
    '''Interprets the string of classes that the website has provided
    
    Arguments: the string of classes that was provided by the website

    Returns: a list of classes that problem.py can take in
    '''
    takenClasses = []

    return takenClasses


def generateSchedule():
    '''Generates a schedule with taken classes as the initial state for a
    search by problem.py, then calls printSchedule which prints the output
    onto the command line

    Main function of websiteWrapper.py'''

    takenClasses = interpretInput()

    # make stuff happen

    printSchedule(takenClasses)

def printSchedule(returnedSchedule):
    '''Takes a schedule (list of semesters, where each semester is a list of
    classes) and prints it, formatted, onto the command line'''
    pass



#generateSchedule()

